#!/usr/bin/env bash
#
# Copyright 2019, The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function run_functiontests() {
    if ! m aidegen_functional_test; then
        printf "\nFail to build aidegen_functional_test.\n"
        exit 1
    fi
    if ! aidegen_functional_test-dev -b; then
        printf "\nFail to run aidegen_functional_test.\n"
        exit 1
    fi
}

function check_env() {
    if [ -z "$ANDROID_BUILD_TOP" ]; then
        printf "\nMissing ANDROID_BUILD_TOP env variable. Please run 'lunch' first.\n"
        exit 1
    fi
    function m() {
        pushd $ANDROID_BUILD_TOP
        build/soong/soong_ui.bash --make-mode "$@"
        popd
    }
}

check_env
m clean
run_functiontests
